version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: carbooking-mysql
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: libutti
      MYSQL_DATABASE: carbooking
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbooking-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data: