version: '3.8'

services:
  app:
    image: stackoverrage/carbooking:latest
    container_name: carbooking-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.1.28:3306/carbooking?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=enrico
      - SPRING_DATASOURCE_PASSWORD=enrico
    network_mode: "host"